# Generated by Django 4.2.1 on 2023-05-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("sobrenome", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("1", "Pessoa Fisica"), ("2", "Pessoa Juridica")],
                        max_length=10,
                    ),
                ),
                ("telefone", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
