# Generated by Django 4.2.1 on 2023-05-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="endereco",
        ),
        migrations.AddField(
            model_name="address",
            name="client",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="company.clients",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="clients",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="company.clients",
            ),
            preserve_default=False,
        ),
    ]
