# Generated by Django 4.2.1 on 2023-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clients",
            old_name="sobrenome",
            new_name="bairro",
        ),
        migrations.RenameField(
            model_name="clients",
            old_name="telefone",
            new_name="cidade",
        ),
        migrations.AddField(
            model_name="clients",
            name="email",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clients",
            name="estado",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clients",
            name="telefone1",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clients",
            name="telefone2",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
