# Generated by Django 4.2.1 on 2023-05-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="cidade",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="estado",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="rua",
            new_name="street",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="endereco",
        ),
        migrations.AddField(
            model_name="address",
            name="client",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="company.clients",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="client",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="company.clients",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
