# Generated by Django 4.2.1 on 2023-06-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="cep",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="telefone1",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="telefone2",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
