# Generated by Django 4.2.1 on 2023-05-23 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
        migrations.DeleteModel(
            name="Materials",
        ),
        migrations.DeleteModel(
            name="Services",
        ),
    ]
