# Generated by Django 4.2.1 on 2023-05-18 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilCompany",
        ),
    ]
