# Generated by Django 4.2.1 on 2023-05-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_rename_sobrenome_clients_bairro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="bairro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="cidade",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="estado",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="telefone2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="tipo",
            field=models.CharField(
                choices=[("1", "Pessoa Fisica"), ("2", "Pessoa Juridica")],
                max_length=10,
                null=True,
            ),
        ),
    ]
