# Generated by Django 4.2.1 on 2023-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_rename_cidade_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="telefone1",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
