# Generated by Django 4.2.1 on 2023-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_clients_bairro_alter_clients_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="telefone2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
