# Generated by Django 4.2.1 on 2023-05-12 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_address_street_alter_contacts_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="client",
            new_name="client_id",
        ),
    ]
