# Generated by Django 4.2.1 on 2023-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_clients_telefone2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="bairro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="cidade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="estado",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("1", "Pessoa Fisica"), ("2", "Pessoa Juridica")],
                max_length=10,
                null=True,
            ),
        ),
    ]
