# Generated by Django 4.2.1 on 2023-06-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_budgets", models.CharField(max_length=10, unique=True)),
                ("reference", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "situation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Cancelado", "Cancelado"),
                            ("Em andamento", "Em andamento"),
                            ("Concluido", "Concluido"),
                        ],
                        default="Pendente",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("validity", models.DateField(blank=True, null=True)),
                ("term", models.CharField(blank=True, max_length=100, null=True)),
                ("obs", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.clients",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Totals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_services",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "total_materials",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("discount", models.CharField(blank=True, max_length=500, null=True)),
                ("parcels", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "total_final",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "id_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descript", models.CharField(max_length=500)),
                ("details", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("amount", models.TextField(blank=True, null=True)),
                ("total", models.TextField(blank=True, null=True)),
                (
                    "id_budget",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Sem desconto"),
                            ("valor", "Valor"),
                            ("porcentagem", "Porcentagem"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a vista", "a vista"),
                            ("sinal", "sinal"),
                            ("parcelas", "parcelas"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "methods",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "Pix"),
                            ("tranferencia", "Tranferencia"),
                            ("credito", "Cartao de Credito"),
                            ("debito", "Cartao de Debito"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                ("obs", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "id_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descript", models.CharField(blank=True, max_length=500, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("amount", models.TextField(blank=True, null=True)),
                ("total", models.TextField(blank=True, null=True)),
                (
                    "id_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
    ]
