# Generated by Django 4.2.1 on 2023-05-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0002_delete_budget_delete_materials_delete_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_budgets", models.IntegerField(unique=True)),
                ("reference", models.CharField(blank=True, max_length=500, null=True)),
                ("validity", models.DateField()),
                ("term", models.DateField(blank=True, null=True)),
                ("obs", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.clients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descript", models.CharField(max_length=500)),
                ("details", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                (
                    "id_budget",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Valor"), ("2", "Porcentagem")],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("1", "a vista"), ("2", "sinal"), ("3", "parcelas")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "methods",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Dinheiro"),
                            ("2", "Pix"),
                            ("3", "Tranferencia"),
                            ("4", "Cartao de Credito"),
                            ("5", "Cartao de Debito"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "id_budget",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("descript", models.CharField(max_length=500)),
                ("details", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                (
                    "id_budget",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgets",
                    ),
                ),
            ],
        ),
    ]
