# Generated by Django 4.2.1 on 2023-05-26 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgets",
            name="user_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budgets",
            name="number_budgets",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
