# Generated by Django 4.2.1 on 2023-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgets",
            name="number_budgets",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
