# Generated by Django 4.2.1 on 2023-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_budgets_user_id_alter_budgets_number_budgets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgets",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="budgets",
            name="term",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="budgets",
            name="validity",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materials",
            name="amount",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materials",
            name="price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materials",
            name="total",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="amount",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="total",
            field=models.TextField(blank=True, null=True),
        ),
    ]
