# Generated by Django 4.2.1 on 2023-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0003_remove_budgets_user_id_alter_budgets_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgets",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Pendente"),
                    ("2", "Aprovado"),
                    ("3", "Cancelado"),
                    ("4", "Em andamento"),
                    ("5", "Concluido"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
