# Generated by Django 4.2.1 on 2023-06-04 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0004_budgets_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgets",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="budgets",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Pendente"),
                    ("2", "Aprovado"),
                    ("3", "Cancelado"),
                    ("4", "Em andamento"),
                    ("5", "Concluido"),
                ],
                default="1",
                max_length=500,
                null=True,
            ),
        ),
    ]
