# Generated by Django 4.2.1 on 2023-06-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0005_budgets_user_alter_budgets_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgets",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Cancelado", "Cancelado"),
                    ("Em andamento", "Em andamento"),
                    ("Concluido", "Concluido"),
                ],
                default="1",
                max_length=500,
                null=True,
            ),
        ),
    ]
