# Generated by Django 4.2.1 on 2023-06-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0006_alter_budgets_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materials",
            name="photo",
        ),
        migrations.AlterField(
            model_name="materials",
            name="descript",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
