# Generated by Django 4.2.1 on 2023-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0008_payments_obs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a vista", "a vista"),
                    ("sinal", "sinal"),
                    ("parcelas", "parcelas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="discount",
            field=models.CharField(
                blank=True,
                choices=[("valor", "Valor"), ("porcentagem", "Porcentagem")],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="methods",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dinheiro", "Dinheiro"),
                    ("Pix", "Pix"),
                    ("Tranferencia", "Tranferencia"),
                    ("credito", "Cartao de Credito"),
                    ("debito", "Cartao de Debito"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="obs",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
