# Generated by Django 4.2.1 on 2023-05-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editperfilcompany",
            name="email",
            field=models.EmailField(
                default="", max_length=254, unique=True, verbose_name="email"
            ),
            preserve_default=False,
        ),
    ]
