# Generated by Django 4.2.1 on 2023-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_perfilcompany_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilcompany",
            name="razaoSocial",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
