# Generated by Django 4.2.1 on 2023-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_perfilcompany_razaosocial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilcompany",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="perfilcompany",
            name="razaoSocial",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
