# Generated by Django 4.2.1 on 2023-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_perfilcompany_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsertLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
