# Generated by Django 4.2.1 on 2023-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_insertlogo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InsertLogo",
        ),
        migrations.AddField(
            model_name="editperfilcompany",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
